---
kind: pipeline
name: x86_64

steps:
  - name: build tagged image
    image: plugins/docker
    settings:
      repo: plusminusio/mastodon
      auto_tag: true
      username: mohemohe
      password:
        from_secret: dockerhub_password
      dockerfile: tagged.Dockerfile
      squash: true
    when:
      branch:
        - master
      event:
        - tag

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build tagged image
    image: plugins/docker
    settings:
      repo: plusminusio/mastodon
      auto_tag: true
      auto_tag_suffix: arm64
      username: mohemohe
      password:
        from_secret: dockerhub_password
      dockerfile: tagged-arm64.Dockerfile
      squash: true
    when:
      branch:
        - master
      event:
        - tag
