---
kind: pipeline
name: default

steps:
  - name: slack notification on start
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      template: >
        {{repo.owner}}/{{repo.name}} ({{build.branch}}) build #{{build.number}} start: {{build.link}}
    when:
      branch:
        - master
        - staging
      event:
        - push
        - tag

  - name: build staging image
    image: plugins/docker
    settings:
      repo: plusminusio/mastodon
      tag: staging
      username: mohemohe
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - staging
      event:
        - push

  - name: build latest image
    image: plugins/docker
    settings:
      repo: plusminusio/mastodon
      tag: latest
      username: mohemohe
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - master
      event:
        - push

  - name: build tagged image
    image: plugins/docker
    settings:
      repo: plusminusio/mastodon
      auto_tag: true
      username: mohemohe
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - master
      event:
        - tag

  - name: slack notification on complete
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      template: >
        {{#success build.status}}
          {{repo.owner}}/{{repo.name}} ({{build.branch}}) build #{{build.number}} succeeded: {{build.link}}
        {{else}}
          {{repo.owner}}/{{repo.name}} ({{build.branch}}) build #{{build.number}} failed: {{build.link}}
        {{/success}}
    when:
      branch:
        - master
        - staging
      event:
        - push
        - tag
      status:
        - success
        - failure
