name: dispatch build image

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
        description: target branch
      tag:
        type: string
        required: true
        description: docker image tag

concurrency:
  group: build-${{ github.ref }}

jobs:
  build_amd64:
    runs-on: buildjet-4vcpu-ubuntu-2204

    steps:
      - uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": ":loading: 𝙗𝙪𝙞𝙡𝙙 𝙨𝙩𝙖𝙧𝙩\n\ndocker image: plusminusio/mastodon:${{ github.event.inputs.tag }}\nworkflow: ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"}'

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: plusminusio/mastodon:${{ github.event.inputs.tag }}

      - if: success()
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": "☺️ 𝙗𝙪𝙞𝙡𝙙 𝙨𝙪𝙘𝙘𝙚𝙨𝙨\n\ndocker image: plusminusio/mastodon:${{ github.event.inputs.tag }}\nworkflow: ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"}'

      - if: failure()
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": "😩 𝙗𝙪𝙞𝙡𝙙 𝙛𝙖𝙞𝙡𝙪𝙧𝙚\n\ndocker image: plusminusio/mastodon:${{ github.event.inputs.tag }}\nworkflow: ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"}'

  build_arm64:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    steps:
      - uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": ":loading: 𝙗𝙪𝙞𝙡𝙙 𝙨𝙩𝙖𝙧𝙩\n\ndocker image: plusminusio/mastodon:${{ github.event.inputs.tag }}-arm64\nworkflow: ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"}'

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: plusminusio/mastodon:${{ github.event.inputs.tag }}-arm64

      - if: success()
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": "☺️ 𝙗𝙪𝙞𝙡𝙙 𝙨𝙪𝙘𝙘𝙚𝙨𝙨\n\ndocker image: plusminusio/mastodon:${{ github.event.inputs.tag }}-arm64\nworkflow: ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"}'

      - if: failure()
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: https://mstdn.plusminus.io/api/v1/statuses
          headers: '{"Authorization": "Bearer ${{ secrets.MASTODON_TOKEN }}"}'
          body: '{"status": "😩 𝙗𝙪𝙞𝙡𝙙 𝙛𝙖𝙞𝙡𝙪𝙧𝙚\n\ndocker image: plusminusio/mastodon:${{ github.event.inputs.tag }}-arm64\nworkflow: ${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"}'
